export const pricing = [
  {
    id: "tier1",
    title: "TIER 1/Basic",
    description: "Simplify finances affordably.",
    currency: "IDR",
    color: "blue",
    price: 249000,
    discount: 0.45,
    features: [
      "Recording incoming goods",
      "Recording outgoing goods",
      "Recording profit results",
    ],
  },
  {
    id: "tier2",
    title: "TIER 2/Business",
    currency: "IDR",
    color: "rose",
    price: 559000,
    discount: 0.42,
    description: "Optimize mid-sized business operations.",
    features: [
      "Recording incoming and outgoing goods",
      "Recording profits",
      "Can analyze sales results with CHART",
      "7x24 hours support",
    ],
  },
  {
    id: "tier3",
    title: "TIER 3/Entrepreneur",
    description: "Unleash growth potential with advanced tools.",
    currency: "IDR",
    color: "blue",
    price: 1100000,
    discount: 0.35,
    features: [
      "Record incoming and outgoing goods",
      "Recording profits",
      "Can analyze sales results with CHART",
      "7x24 hours support",
      "Export data to Excel",
      "AI Income prediction",
    ],
  },
];
